### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by mr-bat** [soachishti/moss.py#10]
Why doesn't the project have a decent documentation? I had to read the source code to figure out the library.

**Comment by soachishti** [comment]
It is good to have documentation. There is a snippet file named `moss_usage.py`, containing all the functionality this small library provide, did you came across that.

**Comment by soachishti** [comment]
I have no plan for documentation, I believe examples are self explanatory for this module. In case of any other issue do let us know here.

Closing this issue.
