### ISSUE TITLE
0 size file causing issues

### ISSUE THREAD

**Issue by martin5696** [soachishti/moss.py#17]
For my use case, there is a 0 sized file as part of the submission which causes an exception from the following recent change:
`and os.path.getsize(file_path) > 0`

I'm wondering what the purpose of this additional condition is and whether it's necessary?

**Comment by soachishti** [comment]
Hi, We had an issue when sending a file of size 0 to Moss server. Check out this pull request (#13) for detail.

**Comment by martin5696** [comment]
Ok, thanks. I'll figure out a workaround.
