### ISSUE TITLE
Sent Web Page Not Found

### ISSUE THREAD

**Issue by djpt05** [soachishti/moss.py#23]
I've tried running MOSS a few times this morning.  When I receive the generated HTML page back from MOSS I'm getting a 404 not found when I try to go to that page.  

I've tried about a dozen times this morning and keep getting 404 for all the newly generated pages.  I have used this script many times successfully in the past.

**Comment by soachishti** [comment]
Hi, just check MOSS and seems fine. Is it working for you?

**Comment by djpt05** [comment]
Yes it came back to life about 7 hours later. Sorry I forgot to update

**Comment by soachishti** [comment]
Np, Thanks for the response. Closing #23.
