### ISSUE TITLE
Problem with cpp submission 

### ISSUE THREAD

**Issue by AlexKohanim** [soachishti/moss.py#24]
Here is my script,

```#!/usr/bin/env python3

try:
    import mosspy
except:
    print("You are missing a dependency, try running")
    print("pip install mosspy")
    print("You might need to use pip3 and/or sudo depending on your OS")
from pathlib import Path
import sys

# This ID is the default one, I use my own when running
userid = 987654321

languageMap = {"java": [".java"], "cpp": [".cpp", ".h"]}

# for compatibility with Windows and those who don't know about the execution flag
n = 2 if sys.argv[0].startswith("py") else 1

language = sys.argv[n] if len(sys.argv) > n else input("Please enter the language (java or cpp): ")

mossLanguage = "cc" if language == "cpp" else language

m = mosspy.Moss(userid, mossLanguage)

pathlist = []

for extension in languageMap[language.lower()]:
    pathlist += Path(".").glob('**/*' + extension)

for path in pathlist:
    if "__MACOSX" not in str(path):
        m.addFile(str(path))

print(len(pathlist), "files found")
print(pathlist)

print("Sending Report, this might take a while...")
print("Consider Grabing some Coffee or a Snack.")

url = m.send()

print ("Report Url: " + url)
```

I also used cpp as the language and get the same problem.
The script gets stuck with: "recv = s.recv(1024)"
Any help would be nice.

**Comment by soachishti** [comment]
You will need to enter your own userid, '987654321' is dummy.

**Comment by AlexKohanim** [comment]
I did, just as an example I put the default one so others wouldn't take mine. 

Do you think that if I have a file that is larger than 1 megabyte that the program would hang on it?

**Comment by AlexKohanim** [comment]
I ran nethogs to check the network usage of the program. it seems to be running 8 process when in use (I have 8 virtual cores, is that why?). Anyway it the program works normally now [Even did a run without nethogs, took longer than with running nethogs but it worked]. 

Thank you for sitting with me through this one.

**Comment by soachishti** [comment]
Good to hear that it worked. 

Just to add here, script make single connection for communicating with Moss server. However, If you are downloading report using `mosspy.download_report(...)` then script create thread based on parameter: connections (default=4).
