### ISSUE TITLE
addBaseFile() doesn't seems to work

### ISSUE THREAD

**Issue by Bhupesh-V** [soachishti/moss.py#26]
Adding the base file `submission/a01.py` doesn't seems to work. The code is not ignored by Moss

```python
def code_holder(num1, num2):
    v = 0
    #### YOUR CODE GOES HERE ####
    #### make sure you save the return value in the variable: v
    



    #### DO NOT WRITE AFTER THIS LINE

    return v
```
![gggg](https://user-images.githubusercontent.com/34342551/71304221-c0f73500-23e9-11ea-8b91-bdf8657c4d75.png)

Am I missing something here ?

**Comment by soachishti** [comment]
Hi, I tried similar case using moss shell script and got the same result. Have you tried this with larger/different source code?

FTR, Message about base in Moss shell script
> # The -b option names a "base file".  Moss normally reports all code
> # that matches in pairs of files.  When a base file is supplied,
> # program code that also appears in the base file is not counted in matches.
> # A typical base file will include, for example, the instructor-supplied
> # code for an assignment.  Multiple -b options are allowed.  You should
> # use a base file if it is convenient; base files improve results, but
> # are not usually necessary for obtaining useful information.
> #
> # IMPORTANT: Unlike previous versions of moss, the -b option *always*
> # takes a single filename, even if the -d option is also used.

**Comment by Bhupesh-V** [comment]
Not really, I submitted around 60 exactly similar python files (with no base code) and their were NO results for plagiarism

Quote from _How to Read The Results_
> Moss also excludes all code that appears in too many of the submitted programs.

**Comment by soachishti** [comment]
That's interesting, do share the new findings.
