### ISSUE TITLE
Lambda function invalid syntax

### ISSUE THREAD

**Issue by somyamohanty** [soachishti/moss.py#32]
Error on:

```
  File "test.py", line 19
    url = m.send(lambda file_path, display_name: print('*', end='', flush=True))
                                                     ^
SyntaxError: invalid syntax
```

Not sure whats going on. Using Python 2.7

**Comment by somyamohanty** [comment]
I had actually tried that `url = m.send(lambda file_path, display_name: print '*')`, but seems to give an error too. 

```  File "test.py", line 19
    url = m.send(lambda file_path, display_name: print '*')
                                                     ^
SyntaxError: invalid syntax```

In Python 3.8. The error is:

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    url = m.send(lambda file_path, display_name: print('*', end='', flush=True))
TypeError: send() takes 1 positional argument but 2 were given
```

I had also tired just the `url = m.send()`. That results in an empty report. The userid is changed. Not sure if that is a moss issue of mosspy issue.

**Comment by soachishti** [comment]
I tried with the `moss_usage.py` example with no lambdas and moss is responding with report URL.

![image](https://user-images.githubusercontent.com/922984/92763391-eb8c8200-f3ac-11ea-9298-264abe59b5e4.png)

**Comment by somyamohanty** [comment]
Thanks. I tried that with C files, but something seems to go wrong. It might be a different issue altogether. With the following code. 

```
import mosspy

userid = *******

m = mosspy.Moss(userid, language="c")

m.addFile("./submissions/ch1.c")
m.addFile("./submissions/ch1_3.c")
# m.addFile("./submissions/ch1_2.c")

# print(lambda file_path, display_name: print('*', end='', flush=True))

# progress function optional, run on every file uploaded
# result is submission URL
url = m.send()
print()

print ("Report Url: " + url)

# Save report file
m.saveWebPage(url, "submissions/report.html")

# Download whole report locally including code diff links

mosspy.download_report(url, "submissions/report/", connections=8, log_level=10)
```

When I give it similar files it seems to work. 
![Screen Shot 2020-09-10 at 2 54 27 PM](https://user-images.githubusercontent.com/2720456/92785715-a4cf6580-f375-11ea-9777-5293e053e413.png)

But when I give it different c code files it seems to time out. See below. 
![Screen Shot 2020-09-10 at 2 57 40 PM](https://user-images.githubusercontent.com/2720456/92786164-02fc4880-f376-11ea-886b-163718a5535c.png)

Link to example c code is: https://www.dropbox.com/sh/eigdh9rew0of86t/AAAW2kdB9J5pTkMSxE31zSMSa?dl=0

**Comment by soachishti** [comment]
I ran some samples, I am also getting this time out error on `mosspy.download_report(...)`. I suspect that moss server is restricting downloading of report with 8 connections, however it allows connection after minute to two. 

Try setting it with to `connections=1`. This is put less load on the server.

**Comment by somyamohanty** [comment]
Thanks. Now it looks like it skips over files. If I run `m.addFilesByWildcard("./submissions/c*.c")` in the above code (and `connections=1`), it only sends out a report for two files. http://moss.stanford.edu/results/3/1796715018312

**Comment by soachishti** [comment]
Moss returns report for files which have some similarity.

**Comment by somyamohanty** [comment]
Thanks! Looks like the issues are with moss server. Now it does not seem to work (timeout) with the same code.

**Comment by soachishti** [comment]
For record citing from Moss website (https://theory.stanford.edu/~aiken/moss/).

> April 10, 2020, The dramatic increase in online courses due to the coronavirus pandemic seems to have led to a corresponding dramatic increase in the use of Moss over the last few weeks. (It's not clear why these two things should be related, but it appears they are.) The public server has been moved to a larger machine (more cores and more memory), which should help meet the increased demand. **Difficulties connecting to the server or receiving results are a sign that the server is overloaded at that time; please try again later.** All users are asked to limit submissions to no more than 100/day.

closing this issue.
