### ISSUE TITLE
Explain: Moss also excludes all code that appears in too many of the submitted programs.

### ISSUE THREAD

**Issue by laalamrajesh** [soachishti/moss.py#41]
**Moss also excludes all code that appears in too many of the submitted programs. Thus, all matches reported by Moss fairly accurately approximate the signature of plagiarized code: a passage of similar code in two programs that does not also appear in very many other programs.**

What are the criteria for an above-mentioned statement?
I have run with 41 files and 6 files in those are similar. but in result, those 6 files results are not coming. 
But when I executed with only 6 files i got results.

**Comment by soachishti** [comment]
For Moss algorithm related question, reach out to author on following email aiken@cs.stanford.edu
