### ISSUE TITLE
Eventual ConnectionResetError on file upload

### ISSUE THREAD

**Issue by amandaoneallakeside** [soachishti/moss.py#45]
I've been using MossPy for a while and I love it. It has worked consistently for me in the past. But recently, it has started crashing when I try to compare more than a few files. I've reproduced this 10 times now, and it no longer ever finishes my program without crashing.

Code:
```
m = mosspy.Moss(userid, "python") #Removed userid for privacy

m.addBaseFile("desktop.ini") #Don't have an actual base file, so use this... it's worked in the past.

#Note: this is about 30 files, the largest of which is a few hundred lines of code.
m.addFilesByWildcard("Critters - Milestone 2/*/Lion.java") 

url = m.send(lambda file_path, display_name: print('*', end='', flush=True))

print ("Report Url: " + url)
```

It prints 15-20 asterisks before it crashes, meaning it's: (1) getting through over half the files before crashing, and (2) getting through a different number of files each time, implying it's not crashing because of a particular file.

Stacktrace:
```
File "run_moss.py", line 32, in <module>
    url = m.send(lambda file_path, display_name: print('*', end='', flush=True))
  File "C:\Users\amanda.oneal\Anaconda3\lib\site-packages\mosspy\moss.py", line 131, in send
    self.uploadFile(s, file_path, display_name, index, on_send)
  File "C:\Users\amanda.oneal\Anaconda3\lib\site-packages\mosspy\moss.py", line 104, in uploadFile
    s.send(message.encode())
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

Help?

**Comment by soachishti** [comment]
Hi, It really nice to hear how this script is helping. It seems like the server is rejecting file upload. Can you try uploading the same files using original moss shell script multiple time to confirm the behavior?

Script Link: http://moss.stanford.edu/general/scripts/mossnet

**Comment by amandaoneallakeside** [comment]
Well.. of course, as soon as I posted this, it started working again (both the perl script and the mosspy version). Let's give it a week or so, and if the error doesn't re-appear, I'll close out this issue.

**Comment by amandaoneallakeside** [comment]
Closing because the error seems to have gone away on its own. Will re-open if it starts happening again with any consistency.
