### ISSUE TITLE
Question about the moss connection

### ISSUE THREAD

**Issue by BrokenArrow1404** [soachishti/moss.py#47]
When I use the original moss shell script to upload some codes, it is stuck on the 'OK' and after a very long time (almost 5 mins) it will continue uploading the files. But it returned nothing after the 'Waiting for the server's response'.
Any idea what should I do? 
Thanks a lot.

**Comment by soachishti** [comment]
Hi, Can you the confirm the size of code you are uploading to moss server? In case of load on server, are you observing the same behavior in different time of day?

**Comment by BrokenArrow1404** [comment]
I tried many times and found that should be the sever's problem. I can't use moss just at the midnight.
