### ISSUE TITLE
It seems like m.send() doesn't work, what should I do? Thanks a lot!

### ISSUE THREAD

**Issue by Amy2017new** [soachishti/moss.py#7]
I downloaded the zip and installed the package successfully
➜  sudo pip install moss.py-master.zip

But when I run moss_usage.py, I got this error:
➜  moss.py-master python moss_usage.py
Report URL:
Traceback (most recent call last):
  File "moss_usage.py", line 20, in <module>
    m.saveWebPage(url, "submission/report.html")
  File "/Users/moss.py-master/mosspy/moss.py", line 143, in saveWebPage
    raise Exception("Empty url supplied")
Exception: Empty url supplied

It seems like m.send() doesn't work, what should I do? Thanks a lot!

**Comment by soachishti** [comment]
Hi, You will have to set `userid` in moss_usage file (987654321 is dummy value).

**Comment by Amy2017new** [comment]
Is the userid contained in the Moss account? I've sent the mail to moss@moss.stanford.edu and applied for the account eleven days ago, but I haven't received any reply. Should I keep waiting or apply again?

**Comment by Bhupesh-V** [comment]
> Is the userid contained in the Moss account? I've sent the mail to [moss@moss.stanford.edu](mailto:moss@moss.stanford.edu) and applied for the account eleven days ago, but I haven't received any reply. Should I keep waiting or apply again?

I am having the same problems.
Did you got the email ?
