### ISSUE TITLE
Adding Base Files By Wildcard

### ISSUE THREAD

**Issue by saatviks** [soachishti/moss.py#8]
This doesn't seem like a supported feature currently, and would be nice to have. I'm just getting started with `Moss`, so I'm not sure if there is some reason for not supporting this?

**Comment by soachishti** [comment]
Hi @saatviks 

Good to see you using Moss. I think you missed out `Moss.addFilesByWildcard()` and [moss_usage.py](https://github.com/soachishti/moss.py/blob/master/moss_usage.py).

**Sample Code**
```python
import mosspy
userid = 987654321
m = mosspy.Moss(userid, "python")
m.addFilesByWildcard("submission/a01-*.py") # Here you go.
url = m.send() 
print ("Report URL: " + url)
```
